
server.port=4300
spring.application.name=API-GATEWAY
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.roles=ADMIN
info.app.name=API-GATEWAY
info.app.version=1.0.0

gateway.auth.username=admin
gateway.auth.password=12345
gateway.jwt.secret=mysupersecretkey123456
gateway.jwt.expiration=3600000

